### ISSUE TITLE
error running hook for S_START_COOLTIME_ITEM

### ISSUE THREAD

**Issue by AntiScrewdriver** [KYGAS/Auto-Beeroocher#1]
![image](https://user-images.githubusercontent.com/47073195/62091976-959f6c80-b2c7-11e9-8a70-977b5ab1d149.png)

Hello, been using this mod for a while now. great stuff, but recently got this error, how do i fix it  ?

**Comment by KYGAS** [comment]
The error is fixed, you just need to enable your auto-update and if you are using proxy that doesn't support it, change to TERA Toolbox, it support it. Unless you are on a region that TERA Toolbox doen't support, then just download the module again and it will be fixed. ^^

**Comment by AntiScrewdriver** [comment]
thanks much kygas !
